### ISSUE TITLE
TAs cannot end a queue

### ISSUE THREAD

**Issue by Soreloser2** [pfateev/qdub#50]
Pressing the End queue button as a TA does nothing. Students can still enter the queue and the TA will still respond to them.

**Comment by pfateev** [comment]
@Soreloser2 thanks for pointing this out.

**For team:**
I just pushed changes to `fullstack` branch. "End queue" button now correctly hits the `/activate` route and flips the status of the queue. 
What we're missing is a redirect for the TA as well as a redirect for all the students in the queue, notifying them that the queue has been closed.

**TODO:**
_TA_
- [x] Add a reroute to login page and trigger a new instance with refresh or otherwise.
- [x] Make sure all React state is cleared
- [ ] *** _Improvement:_ back button alert : "are you sure you want to end the queue?"

_Student_
- [ ] It's possible we'll need to add a boolean to the interval GET request on `/queue` so when the active status changes, Students see that change
- [ ] Reroute student
- [ ] Give them a Toast notification
- [ ] Make sure all React state is cleared
